### ISSUE TITLE
Widgets.Tabs

### ISSUE THREAD

**Issue by achirkin** [achirkin/qua-view#28]
Taken from #26 
* [ ] Widgets.Tabs: Handle gracefully cases when we have zero or one tab.
* [x] Widgets.ControlButtons
   - 1. [x] Share button
   - 2. [x] check other buttons
   - 3. [x] stub for luci service run (take Inactive to hide it)
   - 6. [x] Save scenario button: Modal Window takes geometry, image (both not available yet) and text
* [x] rename Widgets.Tabs.Info -> Widgets.Tabs.Reviews
* [ ] "Share" modal window: forgot to center social network' icons and add a little bit of shade to them

Taken from #27 
* [x] Widgets.Tabs.Info:
   - [x] replicate visual appearence of table-thingy on old code. font size, row colors and pointer type need adjustment.
   - [x] Show properties for scenario
   - [x] show properties for selected objects (use `selectedObjIdD`)
   - [x] modify/add properties (using lenses)

**Comment by mb21** [comment]
Display consistent error messages to the user in various places.

- [ ] in `Tabs/Review.hs#renderWriteReview` on error from server

**Comment by achirkin** [comment]
Info tab:
 [ ] prevent table td overflow
 [ ] do not allow to edit multiple rows at once

**Comment by achirkin** [comment]
New update from designers: make all tabs appear in one column, avoiding the need to click on tabs to see object infos.

I propose to do as follows:

  1. keep tabs' headers as-is (just make info the first tab)
  2. make tabs' contents appear one below another; so that clicking on a tab just scrolls the pane to a place where tab content begins.

**Comment by achirkin** [comment]
All of this seems to be implemented by now
