### ISSUE TITLE
Building sometimes rotated 90 degrees 

### ISSUE THREAD

**Issue by jonathanwoenardi** [achirkin/qua-view#8]
How to recreate the error:

```
Base GeoJSON

{
    "features": [   
        {
            "type": "Feature",
            "id": "101",
            "properties": {
                "@id": "101",
                "height": "20",
                "name": "20m Building",
                "type": "multipolygon"
            },
            "geometry": { 
                "type": "Polygon",
                "coordinates": [
                    [ 
                        [ 220, 0 ],
                        [ 223, 0 ],
                        [ 223, 1 ],
                        [ 220, 1 ],
                        [ 220, 0 ]
                    ] 
                ] 
            } 
        }
    ],
    "type": "FeatureCollection"
}

```

1. Upload the GeoJSON. Using the old heuristics, the object will be transformed from WGS'84 to Metric and will look like a flat rectangle.
2. Change the coordinate valued 223 into 224. It will still be transformed from WGS'84 to Metric. However, the rectangle will be rotated 90 degrees.

Note: 
a. Using the new heuristic which is added in branch repair-import-procedure, the bug does not show up, but that does not mean the bug is fixed.
b. I first came up with this issue when working with a metric model, so I think the transformation is not necessary for the bug to come out. However, I have not been able to reproduce the previous encounter.

**Comment by achirkin** [comment]
We observed this problem occasionally, but it was very subtle. I think this might be related to the way I calculated object projections. The idea was to calculate a proper translation+rotation for an object given its absolute coordinates. That is:

  `[Absolute point positions] -> [Relative point positions] + [Transformation matrix]`

Such that the centroid of convex hull (or bounding rectangle?.. don't remember atm) around the object is at origin in the relative coordinate system. This enables the object rotation around vertical axis. The function responsible for this is [`locateMultiPolygon`](https://github.com/achirkin/qua-view/blob/master/src/Program/Model/CityObject.hs#L124). The problem may also hide in [the function that calculates the bounding rectangle](https://github.com/achirkin/qua-view/blob/master/src/Data/Geometry/Structure/PointSet.hs#L211). So we can look into these places to solve the issue.

**Comment by jonathanwoenardi** [comment]
A better way to recreate the error that compatible with the newest master:

```

Root GeoJSON

{
    "srid": 4326,
    "geometry": {
        "features": [
            {
                "type": "Feature",
                "id": "101",
                "properties": {
                    "@id": "101",
                    "height": "200000",
                    "name": "20m Building CORRECT",
                    "type": "multipolygon"
                },
                "geometry": { 
                    "type": "Polygon",
                    "coordinates": [
                        [ 
                            [ 220, 0 ],
                            [ 223, 0 ],
                            [ 223, 1 ],
                            [ 220, 1 ],
                            [ 220, 0 ]
                        ] 
                    ] 
                }
            },
            {
                "type": "Feature",
                "id": "102",
                "properties": {
                    "@id": "102",
                    "height": "200000",
                    "name": "20m Building ERROR",
                    "type": "multipolygon"
                },
                "geometry": { 
                    "type": "Polygon",
                    "coordinates": [
                        [ 
                            [ 220, 0 ],
                            [ 224, 0 ],
                            [ 224, 1 ],
                            [ 220, 1 ],
                            [ 220, 0 ]
                        ] 
                    ] 
                }
            }
        ],
        "type": "FeatureCollection"
    }
}

```

**Comment by jonathanwoenardi** [comment]
Found out that the problem is on the [`gm$minRectAngle`](https://github.com/achirkin/qua-view/jsbits/PointSet.js#L231). The purpose of this function is to calculate the minimum-area oriented rectangle for a convex hull of a polygon. One example input where the function behave incorrectly: [[2, 2], [-2, 2], [-4, -2], [4, -2]].

TODO: Fix or redo the algorithm.
